---
# Kubernetes Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://princekumar201926_db_user:Prince12@cluster0.5ofszap.mongodb.net/?appName=Cluster0"
